### PR TITLE
Add get/set for accel and gyro biases

### PR DESCRIPTION
**Pull request by mariusknaust**
Issue #32

### CODE REVIEW

**Comment by mariusknaust** [comment]
@tchamelot could you test these changes on your board? I successfully use the accel bias in my project.

**Comment by tchamelot** [comment]
> 
> 
> @tchamelot could you test these changes on your board? I successfully use the accel bias in my project.

I will do. I was a bit busy the past few weeks but next week is holidays so I can't promise you anything but I will try to do it ;).

**Comment by tchamelot** [comment]
I am working on it right now. First fun fact, when using the accel biases from `calibrate_at_rest` there is a sign error and the bias is doubled. I don't know if we should do something, but i believe that the fix should be in `calibrate_at_rest`

**Comment by tchamelot** [comment]
It's fine for me except for  the accel bias which are not consistent with `calibrate_at_rest`. Another problem in `calibrate_at_rest` is that it takes the gravity into account but it is not something wanted because the gravity is doubled when the IMU is flipped upside down. Actually this function does not return the biases but the average measure. I should have read the doc before ^^.

**Comment by mariusknaust** [comment]
`calibrate_at_rest` should have the same result as before this PR, doesn’t it? If not, feel free to change it. I’ve tried to keep it untouched, I only removed code duplication. The fact that `calibrate_at_rest` isn’t perfect should be another issue.

**Pull request merged**
